# Generated by Django 5.0.1 on 2025-07-08 05:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('employee_id', models.CharField(help_text='Unique employee identifier', max_length=20, unique=True, verbose_name='Employee ID')),
                ('department', models.CharField(choices=[('quality', 'Quality Assurance'), ('regulatory', 'Regulatory Affairs'), ('warehouse', 'Warehouse'), ('management', 'Management'), ('it', 'Information Technology')], max_length=100, verbose_name='Department')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('preferred_language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=10, verbose_name='Preferred Language')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='Must Change Password')),
                ('password_changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Password Last Changed')),
                ('failed_login_attempts', models.IntegerField(default=0, verbose_name='Failed Login Attempts')),
                ('last_failed_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Failed Login')),
                ('electronic_signature', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Electronic Signature')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature Image')),
                ('is_quality_manager', models.BooleanField(default=False, verbose_name='Is Quality Manager')),
                ('is_document_controller', models.BooleanField(default=False, verbose_name='Is Document Controller')),
                ('can_approve_documents', models.BooleanField(default=False, verbose_name='Can Approve Documents')),
                ('is_trained', models.BooleanField(default=False, verbose_name='Training Completed')),
                ('training_date', models.DateField(blank=True, null=True, verbose_name='Last Training Date')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SecureSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Session Key')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.CharField(max_length=500, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Last Activity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Secure Session',
                'verbose_name_plural': 'Secure Sessions',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Stored separately in case user is deleted', max_length=150, verbose_name='Username')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('login_failed', 'Failed Login Attempt'), ('password_change', 'Password Changed'), ('create', 'Record Created'), ('update', 'Record Updated'), ('delete', 'Record Deleted'), ('view', 'Record Viewed'), ('approve', 'Document Approved'), ('reject', 'Document Rejected'), ('download', 'File Downloaded'), ('print', 'Document Printed')], max_length=50, verbose_name='Action')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Model Name')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='Object ID')),
                ('object_repr', models.CharField(blank=True, max_length=500, verbose_name='Object Representation')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='Old Values')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='New Values')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('reason', models.TextField(blank=True, verbose_name='Reason for Change')),
                ('electronic_signature', models.UUIDField(blank=True, null=True, verbose_name='Electronic Signature')),
                ('signature_meaning', models.CharField(blank=True, help_text='e.g., "I approve this document"', max_length=200, verbose_name='Signature Meaning')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='accounts_au_timesta_40aa9a_idx'), models.Index(fields=['user', '-timestamp'], name='accounts_au_user_id_1110c4_idx'), models.Index(fields=['action', '-timestamp'], name='accounts_au_action_918219_idx')],
            },
        ),
    ]
