# Generated by Django 5.0.1 on 2025-07-08 05:21

import django.core.validators
import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(help_text='e.g., SOP-QA-001', max_length=50, unique=True, verbose_name='Document ID')),
                ('title', models.CharField(max_length=200, verbose_name='Document Title')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Document Title (English)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('document_type', models.CharField(choices=[('sop', 'Standard Operating Procedure'), ('wp', 'Work Instruction'), ('form', 'Form'), ('policy', 'Policy'), ('manual', 'Manual'), ('specification', 'Specification'), ('certificate', 'Certificate'), ('report', 'Report'), ('other', 'Other')], max_length=20, verbose_name='Document Type')),
                ('version', models.CharField(default='1.0', max_length=10, verbose_name='Version')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('published', 'Published'), ('obsolete', 'Obsolete')], default='draft', max_length=20, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Effective Date')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='Next Review Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('file', models.FileField(upload_to=documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])], verbose_name='Document File')),
                ('file_size', models.IntegerField(default=0, verbose_name='File Size (bytes)')),
                ('file_pages', models.IntegerField(blank=True, null=True, verbose_name='Number of Pages')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public Document')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated', max_length=500, verbose_name='Keywords')),
                ('language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=10, verbose_name='Language')),
                ('requires_training', models.BooleanField(default=False, verbose_name='Requires Training')),
                ('is_controlled', models.BooleanField(default=True, verbose_name='Controlled Document')),
                ('retention_years', models.IntegerField(default=5, verbose_name='Retention Period (Years)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_documents', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('departments', models.ManyToManyField(blank=True, limit_choices_to={'department__isnull': False}, related_name='accessible_documents', to=settings.AUTH_USER_MODEL, verbose_name='Accessible to Departments')),
                ('owner', models.ForeignKey(help_text='Responsible for document content and updates', on_delete=django.db.models.deletion.PROTECT, related_name='owned_documents', to=settings.AUTH_USER_MODEL, verbose_name='Document Owner')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_date'],
                'permissions': [('can_approve_document', 'Can approve documents'), ('can_publish_document', 'Can publish documents'), ('can_obsolete_document', 'Can obsolete documents')],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('print', 'Print'), ('email', 'Email')], max_length=20, verbose_name='Access Type')),
                ('access_date', models.DateTimeField(auto_now_add=True, verbose_name='Access Date')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('acknowledged', models.BooleanField(default=False, verbose_name='Acknowledged Reading')),
                ('acknowledgment_date', models.DateTimeField(blank=True, null=True, verbose_name='Acknowledgment Date')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Access Log',
                'verbose_name_plural': 'Document Access Logs',
                'ordering': ['-access_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('name_en', models.CharField(max_length=100, verbose_name='Category Name (English)')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Category Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.documentcategory')),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documentcategory', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('is_review_comment', models.BooleanField(default=False, verbose_name='Review Comment')),
                ('resolved', models.BooleanField(default=False, verbose_name='Resolved')),
                ('resolved_date', models.DateTimeField(blank=True, null=True, verbose_name='Resolved Date')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documents.document')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_comments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Comment',
                'verbose_name_plural': 'Document Comments',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Department')),
                ('external_party', models.CharField(blank=True, max_length=200, verbose_name='External Party')),
                ('copy_number', models.CharField(blank=True, max_length=20, verbose_name='Copy Number')),
                ('distribution_date', models.DateTimeField(auto_now_add=True, verbose_name='Distribution Date')),
                ('receipt_confirmed', models.BooleanField(default=False, verbose_name='Receipt Confirmed')),
                ('confirmation_date', models.DateTimeField(blank=True, null=True, verbose_name='Confirmation Date')),
                ('is_withdrawn', models.BooleanField(default=False, verbose_name='Withdrawn')),
                ('withdrawal_date', models.DateTimeField(blank=True, null=True, verbose_name='Withdrawal Date')),
                ('withdrawal_reason', models.CharField(blank=True, max_length=200, verbose_name='Withdrawal Reason')),
                ('distributed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions_made', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='documents.document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Distribution',
                'verbose_name_plural': 'Document Distributions',
                'ordering': ['-distribution_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=10, verbose_name='Version Number')),
                ('file', models.FileField(upload_to='document_versions/', verbose_name='Version File')),
                ('change_description', models.TextField(verbose_name='Change Description')),
                ('change_reason', models.CharField(max_length=200, verbose_name='Change Reason')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('is_current', models.BooleanField(default=False, verbose_name='Is Current Version')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'verbose_name': 'Document Version',
                'verbose_name_plural': 'Document Versions',
                'ordering': ['-created_date'],
                'unique_together': {('document', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='DocumentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_role', models.CharField(choices=[('reviewer', 'Reviewer'), ('approver', 'Approver'), ('publisher', 'Publisher')], max_length=50, verbose_name='Approval Role')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('requested_date', models.DateTimeField(auto_now_add=True, verbose_name='Requested Date')),
                ('action_date', models.DateTimeField(blank=True, null=True, verbose_name='Action Date')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due Date')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('electronic_signature', models.UUIDField(blank=True, null=True, verbose_name='Electronic Signature')),
                ('signature_meaning', models.CharField(blank=True, max_length=200, verbose_name='Signature Meaning')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Reminder Sent')),
                ('reminder_date', models.DateTimeField(blank=True, null=True, verbose_name='Reminder Date')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_approvals', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='documents.document')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.documentversion')),
            ],
            options={
                'verbose_name': 'Document Approval',
                'verbose_name_plural': 'Document Approvals',
                'ordering': ['requested_date'],
            },
        ),
    ]
