# Generated by Django 5.0.1 on 2025-07-12 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.CharField(help_text='e.g., TRN-QA-001', max_length=50, unique=True, verbose_name='Program ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Title (English)')),
                ('description', models.TextField(verbose_name='Description')),
                ('training_type', models.CharField(choices=[('initial', 'Initial Training'), ('refresher', 'Refresher Training'), ('update', 'Update Training'), ('compliance', 'Compliance Training'), ('technical', 'Technical Training'), ('quality', 'Quality Training'), ('safety', 'Safety Training')], max_length=20, verbose_name='Training Type')),
                ('delivery_method', models.CharField(choices=[('classroom', 'Classroom'), ('online', 'Online'), ('practical', 'Practical'), ('self_study', 'Self Study'), ('blended', 'Blended')], default='classroom', max_length=20, verbose_name='Delivery Method')),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Duration (Hours)')),
                ('passing_score', models.IntegerField(default=80, help_text='Minimum score required to pass', verbose_name='Passing Score %')),
                ('validity_months', models.IntegerField(default=12, help_text='How long the training remains valid', verbose_name='Validity (Months)')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Mandatory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_programs_created', to=settings.AUTH_USER_MODEL)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='required_for', to='training.trainingprogram', verbose_name='Prerequisites')),
                ('related_documents', models.ManyToManyField(blank=True, related_name='training_programs', to='documents.document', verbose_name='Related Documents')),
                ('target_departments', models.ManyToManyField(limit_choices_to={'department__isnull': False}, related_name='required_training_programs', to=settings.AUTH_USER_MODEL, verbose_name='Target Departments')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_programs_conducted', to=settings.AUTH_USER_MODEL, verbose_name='Default Trainer')),
            ],
            options={
                'verbose_name': 'Training Program',
                'verbose_name_plural': 'Training Programs',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('material_type', models.CharField(choices=[('presentation', 'Presentation'), ('document', 'Document'), ('video', 'Video'), ('quiz', 'Quiz'), ('exercise', 'Exercise'), ('reference', 'Reference Material')], max_length=20, verbose_name='Material Type')),
                ('file', models.FileField(upload_to='training_materials/', verbose_name='File')),
                ('file_size', models.IntegerField(default=0, verbose_name='File Size (bytes)')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Mandatory')),
                ('is_downloadable', models.BooleanField(default=True, verbose_name='Downloadable')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded Date')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='training.trainingprogram', verbose_name='Training Program')),
            ],
            options={
                'verbose_name': 'Training Material',
                'verbose_name_plural': 'Training Materials',
                'ordering': ['program', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('attended', 'Attended'), ('completed', 'Completed'), ('failed', 'Failed'), ('absent', 'Absent'), ('cancelled', 'Cancelled')], default='enrolled', max_length=20, verbose_name='Status')),
                ('attendance_date', models.DateTimeField(blank=True, null=True, verbose_name='Attendance Date')),
                ('attendance_signature', models.UUIDField(blank=True, null=True, verbose_name='Attendance Signature')),
                ('pre_test_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pre-Test Score')),
                ('post_test_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Post-Test Score')),
                ('test_date', models.DateTimeField(blank=True, null=True, verbose_name='Test Date')),
                ('certificate_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Certificate Number')),
                ('certificate_issued_date', models.DateField(blank=True, null=True, verbose_name='Certificate Issued Date')),
                ('certificate_expiry_date', models.DateField(blank=True, null=True, verbose_name='Certificate Expiry Date')),
                ('effectiveness_score', models.IntegerField(blank=True, help_text='1-5 scale', null=True, verbose_name='Training Effectiveness Score')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback')),
                ('enrolled_date', models.DateTimeField(auto_now_add=True, verbose_name='Enrolled Date')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Completed Date')),
                ('electronic_signature', models.UUIDField(blank=True, null=True, verbose_name='Electronic Signature')),
                ('signature_date', models.DateTimeField(blank=True, null=True, verbose_name='Signature Date')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to=settings.AUTH_USER_MODEL, verbose_name='Trainee')),
            ],
            options={
                'verbose_name': 'Training Record',
                'verbose_name_plural': 'Training Records',
                'ordering': ['-enrolled_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_relevance', models.IntegerField(help_text='1-5 scale', verbose_name='Content Relevance')),
                ('content_clarity', models.IntegerField(help_text='1-5 scale', verbose_name='Content Clarity')),
                ('content_completeness', models.IntegerField(help_text='1-5 scale', verbose_name='Content Completeness')),
                ('trainer_knowledge', models.IntegerField(help_text='1-5 scale', verbose_name='Trainer Knowledge')),
                ('trainer_presentation', models.IntegerField(help_text='1-5 scale', verbose_name='Trainer Presentation')),
                ('trainer_interaction', models.IntegerField(help_text='1-5 scale', verbose_name='Trainer Interaction')),
                ('facility_rating', models.IntegerField(help_text='1-5 scale', verbose_name='Facility Rating')),
                ('materials_rating', models.IntegerField(help_text='1-5 scale', verbose_name='Materials Rating')),
                ('overall_rating', models.IntegerField(help_text='1-5 scale', verbose_name='Overall Rating')),
                ('would_recommend', models.BooleanField(default=True, verbose_name='Would Recommend')),
                ('strengths', models.TextField(blank=True, verbose_name='Strengths')),
                ('improvements', models.TextField(blank=True, verbose_name='Areas for Improvement')),
                ('additional_comments', models.TextField(blank=True, verbose_name='Additional Comments')),
                ('submitted_date', models.DateTimeField(auto_now_add=True, verbose_name='Submitted Date')),
                ('training_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='training.trainingrecord', verbose_name='Training Record')),
            ],
            options={
                'verbose_name': 'Training Evaluation',
                'verbose_name_plural': 'Training Evaluations',
                'ordering': ['-submitted_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(help_text='Auto-generated', max_length=50, unique=True, verbose_name='Session Code')),
                ('scheduled_date', models.DateTimeField(verbose_name='Scheduled Date')),
                ('actual_date', models.DateTimeField(blank=True, null=True, verbose_name='Actual Date')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20, verbose_name='Status')),
                ('max_participants', models.IntegerField(default=20, verbose_name='Maximum Participants')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='training.trainingprogram', verbose_name='Training Program')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_sessions_conducted', to=settings.AUTH_USER_MODEL, verbose_name='Trainer')),
            ],
            options={
                'verbose_name': 'Training Session',
                'verbose_name_plural': 'Training Sessions',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='training.trainingsession', verbose_name='Training Session'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingrecord',
            unique_together={('trainee', 'session')},
        ),
    ]
